---
version: 2.1

orbs:
  executor-tools: twdps/executor-tools@0.7.0
  op: twdps/onepassword@dev:latest

# ================================================================= global pipeline parameters

parameters:
  context:
    description: circleci context for all jobs
    type: string
    default: twdps-core-labs-team
  shell-options:
    description: shell options for all jobs
    type: string
    default: op run --env-file op.env -- /bin/bash -eo pipefail

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

# ================================================================= workflows

workflows:
  version: 2
  alpine-image-pipeline:
    jobs:
      - executor-tools/dev-release:
          name: alpine-dev-build
          shell: << pipeline.parameters.shell-options >>
          context: << pipeline.parameters.context >>
          dockerfile: Dockerfile.alpine
          image: twdps/circleci-remote-docker
          tag: alpine-edge
          cis-docker-image-scan: true
          docker-cve-scan: true
          severity-threshold: low
          snyk-organization: twdps
          bats-test: true
          test-path: test/circleci_remote_docker_alpine.bats
          entry-point: /bin/ash
          container-name: circleci-remote-docker-alpine-edge
          filters: *on-push-main

      - executor-tools/publish:
          name: alpine-release
          shell: << pipeline.parameters.shell-options >>
          context: << pipeline.parameters.context >>
          pull-tag: alpine-edge
          tag-annotation: alpine-
          image: twdps/circleci-remote-docker
          release-tag: alpine-stable
          filters: *on-tag-main

  slim-image-pipeline:
    jobs:
      - executor-tools/machine-executor-dev-release:
          name: slim-dev-build
          context: << pipeline.parameters.context >>
          dockerfile: Dockerfile.slim
          image: twdps/circleci-remote-docker
          tag: slim-edge
          bats-test: true
          docker-cve-scan: true
          severity-threshold: medium
          snyk-organization: twdps
          test-path: test/circleci_remote_docker_slim.bats
          entry-point: /bin/bash
          container-name: circleci-remote-docker-slim-edge
          after-checkout:
            - op/env:
                env-file: op.env
            # - run:
            #     name: inject environment variables
            #     command: |
            #       op inject -i op.env -o $BASH_ENV
            #       source $BASH_ENV
          filters: *on-push-main

      - executor-tools/publish:
          name: slim-release
          shell: << pipeline.parameters.shell-options >>
          context: << pipeline.parameters.context >>
          pull-tag: slim-edge
          tag-annotation: slim-
          image: twdps/circleci-remote-docker
          release-tag: slim-stable
          filters: *on-tag-main

  generate-release-notes:
    jobs:
      - executor-tools/release:
          shell: << pipeline.parameters.shell-options >>
          context: << pipeline.parameters.context >>
          on-tag: true
          filters: *on-tag-main

  # builds nightly from .unpinned Dockerfile in order to test the latest base image and installed packages
  circleci-remote-docker-monthly-build:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - executor-tools/dev-release:
          name: alpine-nightly-build
          shell: << pipeline.parameters.shell-options >>
          context: << pipeline.parameters.context >>
          dockerfile: Dockerfile.alpine
          image: twdps/circleci-remote-docker
          tag: alpine-edge
          cis-docker-image-scan: true
          docker-cve-scan: true
          severity-threshold: low
          snyk-organization: twdps
          bats-test: true
          test-path: test/circleci_remote_docker_alpine.bats
          entry-point: /bin/ash
          container-name: circleci-remote-docker-alpine-edge

      - executor-tools/dev-release:
          name: slim-nightly-build
          context: << pipeline.parameters.context >>
          dockerfile: Dockerfile.slim
          image: twdps/circleci-remote-docker
          tag: slim-edge
          bats-test: true
          docker-cve-scan: true
          severity-threshold: high
          snyk-organization: twdps
          test-path: test/circleci_remote_docker_slim.bats
          entry-point: /bin/bash
          container-name: circleci-remote-docker-slim-edge
          after-checkout:
            - op/env:
                env-file: op.env
            # - run:
            #     name: inject environment variables
            #     command: |
            #       op inject -i op.env -o $BASH_ENV
            #       source $BASH_ENV
